target 'TFLogger', :exclusive => true do
  pod "TFLogger", :path => "../TFLogger.podspec"
  pod 'CocoaLumberjack'
end

target 'Tests', :exclusive => true do
  pod "TFLogger", :path => "../"

  pod 'Kiwi'
end
